### ISSUE TITLE
Environment Variables passing to Forge

### ISSUE THREAD

**Issue by samshupac** [mehrancodes/laravel-harbor#101]
I'm experiencing errors from Harbor that relate to processing of environment variables:

```
$ harbor provision
  INFO    Start finding the server.
  INFO    Finding the associated site.
  INFO    Processing update of environment variables.
[2024-04-11 12:24:08] development.ERROR: Undefined array key 1 {"exception":"[object] (ErrorException(code: 0): Undefined array key 1 at /composer/vendor/mehrancodes/laravel-harbor/app/Actions/MergeEnvironmentVariables.php:53)
[stacktrace]
#0 /composer/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /composer/vendor/mehrancodes/laravel-harbor/app/Actions/MergeEnvironmentVariables.php(53): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()
#2 /composer/vendor/mehrancodes/laravel-harbor/app/Actions/MergeEnvironmentVariables.php(31): App\\Actions\\MergeEnvironmentVariables->searchReplaceExistingVariables()
#3 /composer/vendor/lorisleiva/laravel-actions/src/Concerns/AsObject.php(24): App\\Actions\\MergeEnvironmentVariables->handle()
#4 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/UpdateEnvironmentVariables.php(47): App\\Actions\\MergeEnvironmentVariables::run()
#5 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/UpdateEnvironmentVariables.php(36): App\\Services\\Forge\\Pipeline\\UpdateEnvironmentVariables->getBothEnvsMerged()
#6 /composer/vendor/illuminate/pipeline/Pipeline.php(184): App\\Services\\Forge\\Pipeline\\UpdateEnvironmentVariables->__invoke()
#7 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/EnableQuickDeploy.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#8 /composer/vendor/illuminate/pipeline/Pipeline.php(184): App\\Services\\Forge\\Pipeline\\EnableQuickDeploy->__invoke()
#9 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/ObtainLetsEncryptCertification.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#10 /composer/vendor/illuminate/pipeline/Pipeline.php(184): App\\Services\\Forge\\Pipeline\\ObtainLetsEncryptCertification->__invoke()
#11 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/InstallGitRepository.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#12 /composer/vendor/illuminate/pipeline/Pipeline.php(184): App\\Services\\Forge\\Pipeline\\InstallGitRepository->__invoke()
#13 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/CreateDatabase.php(28): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#14 /composer/vendor/illuminate/pipeline/Pipeline.php(184): App\\Services\\Forge\\Pipeline\\CreateDatabase->__invoke()
#15 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/NginxTemplateSearchReplace.php(31): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#16 /composer/vendor/illuminate/pipeline/Pipeline.php(184): App\\Services\\Forge\\Pipeline\\NginxTemplateSearchReplace->__invoke()
#17 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/OrCreateNewSite.php(35): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#18 /composer/vendor/illuminate/pipeline/Pipeline.php(184): App\\Services\\Forge\\Pipeline\\OrCreateNewSite->__invoke()
#19 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/FindSite.php(32): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /composer/vendor/illuminate/pipeline/Pipeline.php(184): App\\Services\\Forge\\Pipeline\\FindSite->__invoke()
#21 /composer/vendor/mehrancodes/laravel-harbor/app/Services/Forge/Pipeline/FindServer.php(34): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#22 /composer/vendor/illuminate/pipeline/Pipeline.php(184): App\\Services\\Forge\\Pipeline\\FindServer->__invoke()
#23 /composer/vendor/illuminate/pipeline/Pipeline.php(119): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#24 /composer/vendor/mehrancodes/laravel-harbor/app/Commands/ProvisionCommand.php(69): Illuminate\\Pipeline\\Pipeline->then()
#25 /composer/vendor/illuminate/container/BoundMethod.php(36): App\\Commands\\ProvisionCommand->handle()
#26 /composer/vendor/illuminate/container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#27 /composer/vendor/illuminate/container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#28 /composer/vendor/illuminate/container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#29 /composer/vendor/illuminate/container/Container.php(662): Illuminate\\Container\\BoundMethod::call()
#30 /composer/vendor/illuminate/console/Command.php(211): Illuminate\\Container\\Container->call()
#31 /composer/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute()
#32 /composer/vendor/illuminate/console/Command.php(181): Symfony\\Component\\Console\\Command\\Command->run()
#33 /composer/vendor/symfony/console/Application.php(1096): Illuminate\\Console\\Command->run()
#34 /composer/vendor/symfony/console/Application.php(324): Symfony\\Component\\Console\\Application->doRunCommand()
#35 /composer/vendor/symfony/console/Application.php(175): Symfony\\Component\\Console\\Application->doRun()
#36 /composer/vendor/laravel-zero/foundation/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run()
#37 /composer/vendor/laravel-zero/framework/src/Kernel.php(97): Illuminate\\Foundation\\Console\\Kernel->handle()
#38 /composer/vendor/mehrancodes/laravel-harbor/harbor(37): LaravelZero\\Framework\\Kernel->handle()
#39 /composer/vendor/bin/harbor(119): include('...')
#40 {main}
"} 
   ErrorException 
  Undefined array key 1
  at /composer/vendor/mehrancodes/laravel-harbor/app/Actions/MergeEnvironmentVariables.php:53
     49▕ 
     50▕                 continue;
     51▕             }
     52▕ 
  ➜  53▕             [$key, $value] = explode('=', $variable, 2);
     54▕ 
     55▕             if (empty($key)) {
     56▕                 $this->warning("No key found for the assigned value \"$value\" inside your environment variables! Make sure to remove it.");
     57▕
```

Is there something incorrect in my gitlab-ci.yml file?

```
harbor-provision-staging-site:
  stage: deploy
  variables:
    FORGE_TOKEN: XXXXXXX
    FORGE_SERVER: XXXXXX
    FORGE_GIT_PROVIDER: gitlab
    FORGE_GIT_REPOSITORY: $CI_MERGE_REQUEST_PROJECT_PATH
    FORGE_GIT_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    FORGE_DOMAIN: sub-domain.domain.net
    FORGE_SUBDOMAIN_PATTERN: /TM-\d+/
    FORGE_ENV_KEYS: "STRIPE_KEY=XXXX; STRIPE_SECRET=XXXX;"
    FORGE_DEPLOY_SCRIPT: "cd $FORGE_SITE_PATH; git pull origin $FORGE_SITE_BRANCH; composer install; php artisan migrate --force;"
    FORGE_JOB_SCHEDULER: true
    FORGE_DB_CREATION_REQUIRED: true
    FORGE_DB_NAME: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  dependencies: []
  rules:
    - if: $CI_MERGE_REQUEST_PROJECT_PATH != '' # ensures the job only runs in merge request context
      when: manual
  image: kirschbaumdevelopment/laravel-test-runner:8.1
  script:
    # Install Harbor via Composer
    - composer global require mehrancodes/laravel-harbor -q
    # Start Provisioning
    - harbor provision
```

Thanks for any assitance
