### ISSUE TITLE
fatal: No url found for submodule path 'inertia' in .gitmodules

### ISSUE THREAD

**Issue by dhruva81** [mehrancodes/laravel-harbor#108]
I am using laravel-harbour first time. I am receiving following error on forge. 

Please help, is there any configuration needed. 

```
name: preview-provision
on:
  pull_request:
    types: [opened, edited, reopened, ready_for_review]
jobs:
  harbor-provision:
    if: contains(github.event.pull_request.title, '[harbor]')
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    steps:
      - name: Install Harbor via Composer
        run: composer global require mehrancodes/laravel-harbor -q
      - name: Start Provisioning
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_SERVER: ${{ secrets.FORGE_SERVER_ID }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
          FORGE_DOMAIN: ${{ secrets.DOMAIN_NAME }}
          SUBDOMAIN_NAME: pr-${{ github.event.number }}
        run: harbor provision


```

Forge doesn't support Git submodules by default. Please remove the Git submodules from the repository or update your application deployment script.

![image](https://github.com/mehrancodes/laravel-harbor/assets/42173738/0eeb24f9-4b8c-42ea-8c36-29c9fb94aee7)

**Comment by mehrancodes** [comment]
@dhruva81 What does the process of manually deploying your project to Forge look like? Are there any specific actions you need to perform during the deployment?

**Comment by dhruva81** [comment]
@mehrancodes  Thanks for reply.

Earlier I was using forge quick deployment
```
cd /home/forge/cl.abbwc.in
git pull origin $FORGE_SITE_BRANCH

$FORGE_COMPOSER install --no-dev --no-interaction --prefer-dist --optimize-autoloader

( flock -w 10 9 || exit 1
    echo 'Restarting FPM...'; sudo -S service $FORGE_PHP_FPM reload ) 9>/tmp/fpmlock

if [ -f artisan ]; then
    $FORGE_PHP artisan migrate --force
fi

```

Now, I have switched to deployment using github trigger url from github actions .

```

name: Deploy to Production Environment

on:
  release:
    types: [released]

jobs:

   forge-deploy-production:
    name: 'Deploy on production Server'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: jbrooksuk/laravel-forge-action@v1.0.2
        with:
          trigger_url: ${{ vars.FORGE_TRIGGER_URL }}

```

In both cases, deployment is successful.
