### ISSUE TITLE
Issue setting Pull Request comments on organization repo

### ISSUE THREAD

**Issue by hkellou-vitalcare** [mehrancodes/laravel-harbor#112]
Hi there!

Thank you for your work! It's wonderful and I really like it. Nevertheless, I'm trying to setup a laravel-harbor workflow and have been following the steps from the docs. I have this error whenever i use the github comment notifications

```
INFO    Including the site information to the pull request.
FAIL    ---> {"message":"Resource not accessible by integration","documentation_url":"https://docs.github.com/rest/issues/comments#create-an-issue-comment","status":"403"}

   Laravel\Forge\Exceptions\ValidationException 

  The given data failed to pass validation.

  at /composer/vendor/illuminate/support/helpers.php:330
    326▕     function throw_if($condition, $exception = 'RuntimeException', ...$parameters)
    327▕     {
    328▕         if ($condition) {
    329▕             if (is_string($exception) && class_exists($exception)) {
  ➜ 330▕                 $exception = new $exception(...$parameters);
    331▕             }
    332▕ 
    333▕             throw is_string($exception) ? new RuntimeException($exception) : $exception;
    334▕         }
```

I tried to change `github.token` to `secrets.GITHUB_TOKEN`, and tried to open an issue before opening a pull request, still the same error each time with a 403 (authorization error maybe ?).

Here is my code : 
```
harbor-provision:
    needs: laravel-tests
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    steps:
      - name: Install Harbor via Composer
        run: composer global require mehrancodes/laravel-harbor -q
      - name: Start Provisioning
        env:
          INERTIA_SSR_ENABLED: true
          FORGE_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_SERVER: ${{ secrets.FORGE_SERVER_ID }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
          FORGE_DOMAIN: example.com
          FORGE_SUBDOMAIN_PATTERN: '/(?:feat\/|fix\/)?(.*)/'
          FORGE_DEPLOY_SCRIPT: ${{ vars.LARAVEL_DEPLOY_SCRIPT }}
          GIT_COMMENT_ENABLED: true
          GIT_TOKEN: ${{ github.token }}
          GIT_ISSUE_NUMBER: ${{ github.event.number }}
        run: harbor provision
```

I have linked my github account with forge, I have admin access to the org, i did grant access to forge also, so i don't know what's going on. Is there any configuration steps i'm missing?

PS: The provisioning and the teardown works perfectly
