### ISSUE TITLE
Teardown shows 'FAIL ---> Site not found.', but the site exists

### ISSUE THREAD

**Issue by 54853315** [mehrancodes/laravel-harbor#115]
I noticed that there are undeleted preview sites in Forge. Immediately checking the execution logs of Actions shows: **FAIL ---> Site not found.**

![QQ_1726648762438](https://github.com/user-attachments/assets/ac36f383-95b3-47a2-a7e8-76fd6cf537c6)

`preview-teardown.yml` ：

```yaml
name: preview-teardown
on:
  pull_request:
    branches: [dev]
    types: [closed]
jobs:
  harbor-teardown:
    if: |
      github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1
    steps:
      - name: Set FORGE_SUBDOMAIN_PATTERN if head_ref starts with 't'
        if: startsWith(github.head_ref, 't')
        run: echo "FORGE_SUBDOMAIN_PATTERN=/^(t\d{3,8})-(?:.*-.*)/i" >> $GITHUB_ENV
      - name: Install Harbor
        run: composer global require mehrancodes/laravel-harbor -q
      - name: Start Teardown Preview Site
        env:
          FORGE_TOKEN: ${{ secrets.FORGE_API_TOKEN }}
          FORGE_SERVER: ${{ secrets.FORGE_DEV_SERVER_ID }}
          FORGE_GIT_REPOSITORY: ${{ github.repository }}
          FORGE_GIT_BRANCH: ${{ github.head_ref }}
          FORGE_DOMAIN: domain.com
        run: |
          harbor teardown
```

> Please note that my laravel-harbor uses`FORGE_SUBDOMAIN_PATTERN`  to determine the subdomain style based on the branch name:

- It prioritizes matching branch names like "t12345-a-b-c-d", and the domain will be: t12345.domain.com
- If the above branch name is not found, it directly uses the branch name as the domain: branch-name.domain.com

![QQ_1726648839934](https://github.com/user-attachments/assets/def36c98-fa59-4d93-9f98-60c75543c8b7)

In the name: Start Teardown Preview Site step, when printing the environment variables, FORGE_SUBDOMAIN_PATTERN appears, indicating that the condition in the above step: Set FORGE_SUBDOMAIN_PATTERN if head_ref starts with 't' is met. Therefore, a FORGE_SUBDOMAIN_PATTERN is inserted into GitHub's environment variables to ensure the correct subdomain can be found during the teardown phase.

![QQ_1726648256423](https://github.com/user-attachments/assets/fe18a226-5615-4508-ae2c-b04c4173c964)

----------------

So I simulated the content of this Pull Request locally and executed it using the act tool. Surprisingly, it executed **successfully**!

I'm not sure if this is a bug related to the subdomain?

![QQ_1726648984669](https://github.com/user-attachments/assets/6848c79b-47ba-461b-835c-c330f3a81e73)

![QQ_1726648953661](https://github.com/user-attachments/assets/b6fb715e-5926-4a76-850b-fab05643044d)
