### ISSUE TITLE
Setup with Gitlab advice

### ISSUE THREAD

**Issue by samshupac** [mehrancodes/laravel-harbor#99]
For anyone else searching for how to setup Harbor on Gitlab CI this should be useful.
(Based on a pipeline initiated from the merge request context and having Gitlab setup as a Git provider in Forge)

```
harbor-provision-staging-site:
  stage: deploy
  variables:
    FORGE_TOKEN: XXXXX
    FORGE_SERVER: XXXXX
    FORGE_GIT_PROVIDER: gitlab # <-- This is critical and not documented currently
    FORGE_GIT_REPOSITORY: $CI_MERGE_REQUEST_PROJECT_PATH
    FORGE_GIT_BRANCH: $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    FORGE_DOMAIN: XXXXX
  dependencies: []
  rules:
    - if: $CI_MERGE_REQUEST_PROJECT_PATH != '' # ensures the job only runs in merge request context
      when: manual
  image: kirschbaumdevelopment/laravel-test-runner:8.1
  script:
    # Install Harbor via Composer
    - composer global require mehrancodes/laravel-harbor -q
    # Start Provisioning
    - harbor provision
```
